# .github/release-drafter.yml
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '💥 重大更新'
    label: 'major'
  - title: '🚀 新功能'
    labels:
      - 'feature'
      - 'enhancement'
      - 'minor'
      - '新功能'
  - title: '🐛 Bug修复'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - '修复'
  - title: '🧰 维护'
    labels:
      - 'chore'
      - 'dependencies'

version-resolver:
  major:
    labels:
      - 'breaking'
      - 'major'
      - '重大更新'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
      - 'minor'
      - '新功能'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - '修复'
      - '补丁'
  default: patch

autolabeler:
  - label: 'major'
    title:
      - '/breaking/i'
      - '/重大更新/i'
      - '/!:/i'
    body:
      - '/BREAKING CHANGE:/i'
  
  - label: 'minor'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
    title:
      - '/^feat/i'
      - '/^新增/i'
      - '/^添加/i'
  
  - label: 'patch'
    branch:
      - '/fix\/.+/'
      - '/hotfix\/.+/'
    title:
      - '/^fix/i'
      - '/^修复/i'
      - '/^bug/i'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

exclude-labels:
  - 'skip-changelog'

template: |
  ## 更新内容 $RESOLVED_VERSION
  $CHANGES
  
  ### 贡献者
  $CONTRIBUTORS
