# (可选)全局 监听地址
# 默认为 127.0.0.1
HOST: 0.0.0.0
# (可选)全局 监听端口
# 默认为 11111
PORT: 11111

# 认证
AUTH:
  # 是否启用认证
  ENABLE: true
  # 加密密钥
  AUTH_KEY: "114514"
  # 加密密钥过期时间(分钟)
  AUTH_KEY_EXPIRE: 1919810
  # 用户
  AUTH_USER:
    # 用户名
    你好:
      # 用户名
      USER: 114514
      # 密码
      PASS: "114514"


# 录播姬(rectpye)
RECHEME:
  # 名称，没有限制
  Z9001:
      # 录播姬地址
    - URL: http://10.0.0.101:9001


BLREC:
  # (可选)BLREC全局设置 是否启用BLREC认证。如果没有该选项，就默认为 true
  # 默认为 true
  BLREC_BASIC: true
  # (可选)BLREC全局设置 BLREC认证账号密码。如果没有该选项，就默认为 bili2233
  # 默认为 bili2233
  BLREC_BASIC_KEY: bili2233

  # 名称，没有限制
