# (可选)全局 监听地址。默认 127.0.0.1
# 默认 127.0.0.1
HOST: 127.0.0.1
# (可选)全局 监听端口。默认 11111
# 默认 11111
PORT: 11111

# 认证
AUTH:
  # 是否启用认证
  ENABLE: true
  # 加密密钥
  AUTH_KEY: "114514"
  # 加密密钥过期时间 (分钟)
  AUTH_KEY_EXPIRE: 1919810
  # 用户
  AUTH_USER:
    # 用户名
    你好:
      # 用户名
      USER: 114514
      # 密码
      PASS: "114514"

# COOKIE配置
COOKIE:
  # (可选) 是否启用COOKIE
  ## 默认 false
  ENABLE: true
  # (可选)(唯一) COOKIE名称
  ## 默认 空
  C1:
    # (可选) COOKIE服务器地址/cookie值
    ## 默认 空
    VALUE: "http://10.0.0.101:18000"
    # (可选) COOKIE服务器TOKEN
    ## 默认 空
    TOKEN: "1145141919810"
    # (可选) 模式
    ## 默认 random
    ## random 随机: 随机更换
    ## onlysync 只同步: 根据当前录播姬的cookie DedeUserID去向cookie服务器请求获取对应cookie最新值
    MODE: random
    # (可选) 检查间隔 (秒): 检查录播机cookie值是否与cookie服务器一致, 不一致则更换
    ## 默认 3600(1小时)
    CHECK_INTERVAL: 3600
    # (可选) 随机更换间隔 (秒): MODE为random时随机更换cookie的间隔, MODE为onlysync时无效
    ## 默认 86400(1天)
    RANDOM_CHANGE_INTERVAL: 86400

# 录播姬
RECHEME:
  # (可选) 隐藏API输出 URL 地址
  ## 默认 false
  URL_HIDDEN: false
  # (可选)录播姬全局设置 是否启用录播姬认证
  ## 默认 false
  BASIC: false
  # (可选)录播姬全局设置 录播姬认证账号密码
  ## 默认 空
  BASIC_USER: ""
  BASIC_PASS: ""

  # (可选) 录播姬COOKIE配置
  ## 默认 使用全局设置
  COOKIE:
    # (可选) 是否启用COOKIE
    ## 默认 使用全局设置
    ENABLE: true
    # (可选)(唯一) COOKIE名称
    ## 默认 使用全局设置
    C1:
      # (可选) COOKIE服务器地址/cookie值
      ## 默认 使用全局设置
      VALUE: "http://10.0.0.101:18000"
      # (可选) COOKIE服务器TOKEN
      ## 默认 使用全局设置
      TOKEN: "1145141919810"
      # (可选) 模式    
      ## 默认 使用全局设置
      ## random 随机: 随机更换
      ## onlysync 只同步: 根据当前录播姬的cookie DedeUserID去向cookie服务器请求获取对应cookie最新值
      MODE: random
      # (可选) 检查间隔 (秒): 检查录播机cookie值是否与cookie服务器一致, 不一致则更换
      ## 默认 使用全局设置
      CHECK_INTERVAL: 3600
      # (可选) 随机更换间隔 (秒): MODE为random时随机更换cookie的间隔, MODE为onlysync时无效
      ## 默认 使用全局设置
      RANDOM_CHANGE_INTERVAL: 86400

  REC001:
    # 录播姬地址
    - URL: http://114.51.41.91:9810
      # (可选) 隐藏API输出 URL 地址
      ## 默认 使用 RECHEME 全局设置
      URL_HIDDEN: true
      # (可选) 是否启用认证
      ## 默认 使用 RECHEME 全局设置
      BASIC: true
      # (可选) 认证账号密码
      ## 默认 使用 RECHEME 全局设置
      BASIC_USER: "admin"
      BASIC_PASS: "admin"

      # (可选) 录播姬COOKIE配置
      ## 默认 使用录播姬全局设置
      COOKIE:
        # (可选) 是否启用COOKIE
        ## 默认 使用录播姬全局设置
        ENABLE: true
        # (可选)(唯一) COOKIE名称
        ## 默认 使用录播姬全局设置
        C1:
          # (可选) COOKIE服务器地址/cookie值
          ## 默认 使用录播姬全局设置
          VALUE: "http://10.0.0.101:18000"
          # (可选) COOKIE服务器TOKEN
          ## 默认 使用录播姬全局设置
          TOKEN: "1145141919810"
          # (可选) 模式
          ## 默认 使用录播姬全局设置
          ## random 随机: 随机更换
          ## onlysync 只同步: 根据当前录播姬的cookie DedeUserID去向cookie服务器请求获取对应cookie最新值
          MODE: random
          # (可选) 检查间隔(秒): 检查录播机cookie值是否与cookie服务器一致, 不一致则更换
          ## 默认 使用录播姬全局设置
          CHECK_INTERVAL: 3600
          # (可选) 随机更换间隔 (秒): MODE为random时随机更换cookie的间隔, MODE为onlysync时无效
          ## 默认 使用录播姬全局设置
          RANDOM_CHANGE_INTERVAL: 86400

# BLREC
BLREC:
  # (可选) 隐藏API输出 URL 地址
  # 默认 false
  URL_HIDDEN: false
  # (可选)BLREC全局设置 是否启用BLREC认证
  # 默认 true
  BASIC: true
  # (可选)BLREC全局设置 BLREC认证账号密码
  # 默认 bili2233
  BASIC_KEY: "bili2233"

  # 名称，没有限制
  REC101:
    # BLREC地址
    - URL: https://114514.com:1919
      # (可选) 是否启用认证
      # 默认 使用 BLREC 全局设置
      BASIC: true
      # (可选) 认证KEY
      # 默认 使用 BLREC 全局设置
      BASIC_KEY: "88888888"
